### ISSUE TITLE
Feature request for extra commands for Qlab

### ISSUE THREAD

**Issue by dsawyer181** [bitfocus/companion-module-qlab#1]
**osc: Send integer: user be able to set the integer value**
Adjust Cue PreWait Time - by integer: /cue/selected/preWait/- 
Adjust Cue PreWait Time + by integer: /cue/selected/preWait/+
Adjust Cue PostWait Time - by integer: /cue/selected/postWait/-
Adjust Cue PostWait Time + by integer: /cue/selected/postWait/+
Adjust Cue Duration Time - by integer: /cue/selected/duration/-
Adjust Cue Duration Time + by integer: /cue/selected/duration/+

**osc: Send integer:**
Set Cue Continue Mode to "Do Not Continue" : /cue/selected/continueMode 0
Set Cue Continue Mode to "AUTO CONTINUE" : /cue/selected/continueMode 1
Set Cue Continue Mode to "AUTO FOLLOW" : /cue/selected/continueMode 2
Make Cue ARMED : /cue/selected/armed 1
Make Cue DISARMED : /cue/selected/armed 0
Enable Cue Autoload : /cue/selected/autoLoad 1
Disable Cue Autoload : /cue/selected/autoLoad 0

**osc: Send string**
Set Cue Colour to "None" : /cue/selected/colorName none
Set Cue Colour to "Red" : /cue/selected/colorName red
Set Cue Colour to "Yellow" : /cue/selected/colorName yellow
Set Cue Colour to "Green" : /cue/selected/colorName green
Set Cue Colour to "Blue" : /cue/selected/colorName blue
Set Cue Colour to "Purple" : /cue/selected/colorName purple

**Comment by PerRoine** [comment]
All features included in build #292
