### ISSUE TITLE
[Feature request] Automatic button text from cueid

### ISSUE THREAD

**Issue by Bartjee03** [bitfocus/companion-module-qlab#21]
When I enter the cue id in the "Start (cue)" button function. I now have to fill in every button text with the same title of the Qlab cue.
Can that made automatically filled in from the Qlab data?

Osc usage: /cue/{cue_number}/text
https://qlab.app/docs/v4/scripting/osc-dictionary-v4/#text-cue-methods

**Comment by istnv** [comment]
There is a dynamic variable for that. Put `$(qlabfb:q_{num}_name)` in the button text.

**Comment by Bartjee03** [comment]
Nice, its working perfectly! Thx!!
